name: 🐛 Bug Report
description: Report a bug or unexpected behavior with the Electrolux integration
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 
        
        **📝 Quick tip:** The more details you provide, the faster we can help you. But don't worry - only the description is required. Fill out what you can!

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A brief description of the issue. This is the only required field - everything else is optional but helpful!
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (Optional)
      description: If you can reliably reproduce this, let us know how
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior (Optional)
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: false

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version (Recommended)
      description: Which version of Home Assistant are you running?
      placeholder: "e.g., 2026.2.1"
    validations:
      required: false

  - type: input
    id: integration-version
    attributes:
      label: Integration Version (Recommended)
      description: Which version of the Electrolux integration?
      placeholder: "e.g., 3.2.8"
    validations:
      required: false

  - type: dropdown
    id: installation-type
    attributes:
      label: Installation Type (Optional)
      description: How is Home Assistant installed?
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Core
        - Home Assistant Supervised
        - Not sure / Other
    validations:
      required: false

  - type: input
    id: device-model
    attributes:
      label: Device Model (Optional)
      description: Which Electrolux device(s) are affected?
      placeholder: "e.g., Washer-Dryer EW9W161B, Air Conditioner EACS-09HG"
    validations:
      required: false

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics File (Very Helpful!)
      description: |
        **This really helps us fix bugs faster!** Download diagnostics:
        Settings → Devices & Services → Electrolux → Select Device → Download Diagnostics
        
        **Privacy:** Sensitive data (API keys, tokens) is automatically redacted, but please double-check before uploading.
      placeholder: Drag and drop the diagnostics JSON file here (or leave empty)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Debug Logs (Optional but Very Helpful)
      description: |
        If you can, enable debug logging and paste relevant logs:
        
        Add to configuration.yaml:
        ```yaml
        logger:
          default: info
          logs:
            custom_components.electrolux: debug
        ```
        
        Then restart HA, reproduce the issue, and paste logs below.
      placeholder: Paste logs here (or leave empty)
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Screenshots, network setup, recent changes - anything that might help!
      placeholder: Additional context...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Quick Checklist
      description: Just confirming...
      options:
        - label: I searched existing issues to avoid duplicates
          required: false
        - label: I'm using the latest integration version (or at least tried updating)
          required: false
