name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Electrolux integration
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternative approaches...
    validations:
      required: false

  - type: input
    id: device-model
    attributes:
      label: Device Model(s)
      description: Which Electrolux device(s) would this feature apply to?
      placeholder: "e.g., All devices, Air Conditioners, Ovens, etc."
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Example
      description: Provide a specific example of how you would use this feature.
      placeholder: |
        For example:
        - I would use this to automate...
        - This would help me when...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here.
      placeholder: Additional details...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature would be useful to other users, not just me
          required: false
