name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Electrolux integration
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! 🚀
        
        We love hearing your ideas - describe what you'd like to see and we'll consider it!

  - type: textarea
    id: problem
    attributes:
      label: Is this solving a problem? (Optional)
      description: What problem or frustration would this feature address?
      placeholder: "It would be great if..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe the feature you'd like
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative approaches (Optional)
      description: Have you considered other ways to achieve this?
      placeholder: Alternative approaches...
    validations:
      required: false

  - type: input
    id: device-model
    attributes:
      label: Device Model (Optional)
      description: Which devices would this apply to?
      placeholder: "e.g., All devices, Air Conditioners, Ovens, etc."
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: How would you use this? (Optional)
      description: A specific example helps us understand your need
      placeholder: |
        For example:
        - I would use this to automate...
        - This would help me when...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Screenshots, mockups, or additional context
      placeholder: Additional details...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Quick check
      description: Just confirming...
      options:
        - label: I searched existing issues to avoid duplicates
          required: false
        - label: This would benefit other users too (not just me)
          required: false
