name: ❓ Question / Help
description: Ask a question or get help with setup and configuration
title: "[Question]: "
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Need help? We're here for you! 👋
        
        **Tip:** The more context you provide, the better we can help. But just describe your question - everything else is optional!

  - type: textarea
    id: question
    attributes:
      label: What do you need help with?
      description: Describe your question or issue
      placeholder: I need help with...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: What have you tried? (Optional)
      description: Let us know what you've already attempted
      placeholder: |
        I have tried...
        1. ...
        2. ...
    validations:
      required: false

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version (Optional)
      description: Which version are you running?
      placeholder: "e.g., 2026.2.1"
    validations:
      required: false

  - type: input
    id: integration-version
    attributes:
      label: Integration Version (Optional)
      description: Which version of the integration?
      placeholder: "e.g., 3.2.8"
    validations:
      required: false

  - type: input
    id: device-model
    attributes:
      label: Device Model (Optional)
      description: Which Electrolux device(s)?
      placeholder: "e.g., Washer-Dryer EW9W161B"
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration (Optional)
      description: If relevant, share your configuration (remove API keys!)
      placeholder: |
        ```yaml
        # Your configuration here
        ```
      render: yaml
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Screenshots or additional context
      placeholder: Additional details...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Quick check
      description: Just confirming...
      options:
        - label: I checked the documentation
          required: false
        - label: I searched for similar questions
          required: false
