"""Defined catalog of entities for tumble dryer type devices."""

from homeassistant.components.binary_sensor import BinarySensorDeviceClass
from homeassistant.components.button import ButtonDeviceClass
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.components.switch import SwitchDeviceClass
from homeassistant.const import UnitOfMass, UnitOfTime
from homeassistant.helpers.entity import EntityCategory

from .model import ElectroluxDevice

CATALOG_DRYER: dict[str, ElectroluxDevice] = {
    # Basic controls
    "executeCommand": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "string",
            "values": {
                "OFF": {},
                "ON": {},
                "PAUSE": {},
                "RESUME": {},
                "START": {},
                "STOPRESET": {},
            },
        },
        device_class=ButtonDeviceClass.RESTART,
        unit=None,
        entity_category=None,
        entity_icon="mdi:play-pause",
    ),
    # Appliance state and cycle information
    "applianceState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ALARM": {},
                "DELAYED_START": {},
                "END_OF_CYCLE": {},
                "IDLE": {},
                "OFF": {},
                "PAUSED": {},
                "READY_TO_START": {},
                "RUNNING": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tumble-dryer",
    ),
    "cyclePhase": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ANTICREASE": {},
                "COOL": {},
                "CYCLE_PHASE_HIDDEN": {},
                "DRY": {},
                "UNAVAILABLE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tumble-dryer",
    ),
    # Door and remote control status
    "doorState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"CLOSED": {}, "OPEN": {}},
        },
        device_class=BinarySensorDeviceClass.DOOR,
        unit=None,
        entity_category=None,
        entity_icon="mdi:door",
    ),
    # Time and duration controls
    "stopTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 86400,
            "min": 0,
            "step": 3600,
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:clock-end",
        friendly_name="Finish In (Delay)",
    ),
    "minFinishInTime": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {"INVALID_OR_NOT_SET_TIME": {}},
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:clock-start",
        friendly_name="Minimum Finish In Time",
    ),
    # Statistics and counters
    "totalSteamCycleCounter": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Total Steam Cycle Counter",
    ),
    # Load and weight sensors
    "fcOptisenseLoadWeight": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {
                "65408": {},
                "65409": {},
                "65411": {},
                "65412": {},
                "65532": {},
                "NOT_AVAILABLE": {},
                "OVERLOAD": {},
            },
        },
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
        friendly_name="Load Weight",
    ),
    "dryingNominalLoadWeight": ElectroluxDevice(
        capability_info={
            "access": "read",
            "max": 20000,
            "min": 0,
            "step": 1,
            "type": "number",
            "values": {"NOT_AVAILABLE": {}},
        },
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
        friendly_name="Nominal Load Weight",
    ),
    # Appliance mode
    "applianceMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DEMO": {},
                "DIAGNOSTIC": {},
                "NORMAL": {},
                "SERVICE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:cog",
    ),
    # Language setting
    "language": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "CROATIAN": {},
                "CZECH": {},
                "DANISH": {},
                "DUTCH": {},
                "ENGLISH": {},
                "ESTONIAN": {},
                "FINNISH": {},
                "FRENCH": {},
                "GERMAN": {},
                "GREEK": {},
                "HUNGARIAN": {},
                "ITALIAN": {},
                "LATVIAN": {},
                "LITHUANIAN": {},
                "NORWEGIAN": {},
                "POLISH": {},
                "PORTUGUESE": {},
                "ROMANIAN": {},
                "RUSSIAN": {},
                "SLOVAK": {},
                "SLOVENIAN": {},
                "SPANISH": {},
                "SWEDISH": {},
                "SYMBOLS": {},
                "TURKISH": {},
                "UKRANIAN": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:translate",
    ),
    # End of cycle sound
    "endOfCycleSound": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "LONG_SOUND": {},
                "MEDIUM_SOUND": {},
                "NO_SOUND": {},
                "SHORT_SOUND": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:volume-high",
        friendly_name="End of Cycle Sound",
    ),
    # Network interface always on
    "networkInterfaceAlwaysOn": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": "OFF",
            "type": "string",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:wifi",
        friendly_name="Network Always On",
    ),
    # Remote notification
    "remoteNotificationPending": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:bell",
        friendly_name="Remote Notification Pending",
    ),
    # Care level and eco level sensors
    "fCMiscellaneousState/careLevel": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {
                "1": {},
                "2": {},
                "255": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:heart-pulse",
        friendly_name="Care Level",
    ),
    "fCMiscellaneousState/ecoLevel": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {
                "1": {},
                "2": {},
                "3": {},
                "255": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:leaf",
        friendly_name="Eco Level",
    ),
    # User Selections - Program and options
    "userSelections/programUID": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "AUTO_EASY_IRON_PR_EASYIRON_TD": {},
                "BABY_PR_BABY": {},
                "BED_LINEN_PLUS_PR_BEDLINENPLUS": {},
                "BED_LINEN_PLUS_PR_BEDLINENPLUSITA": {},
                "COTTON_PR_COTTONS": {},
                "COTTON_PR_COTTONSECO": {},
                "COTTON_PR_ECO": {},
                "CURTAINS_PR_CURTAINS": {},
                "DOWN_JACKET_PR_DOWN_JACKET": {},
                "DRY_CLEANING_PR_REFRESH": {},
                "DUVET_PR_DUVET": {},
                "EXTRA_DELICATE_PR_DELICATES": {},
                "HYGIENE_PR_HYGIENE": {},
                "JEANS_PR_DENIM": {},
                "JEANS_PR_JEANS": {},
                "LINEN_PR_LINEN": {},
                "MY_DRY_PR_MIXCARE": {},
                "MY_DRY_PR_MIXDRY": {},
                "NA_ALLERGEN_PR_ALLERGEN": {},
                "ONE_ITEM_FAST_PR_ONEITEMFAST": {},
                "OUTD_PROOF_PR_OUTDOOR": {},
                "PETBED_PR_PETHAIR": {},
                "PILLOWS_PR_PILLOW": {},
                "QUICK_PR_QUICK_3KG": {},
                "QUICK_PR_RAPID_3KG": {},
                "SILK_DRY_PR_SILK": {},
                "SKIING_PR_SKIINGGEAR": {},
                "SOCCER_RUGBY_PR_SOCCER_RUGBY": {},
                "SPORTWEAR_PR_SPORTWEAR": {},
                "SYNTHETIC_PR_SYNTHETICS": {},
                "TIMEDRY_PR_DRYINGRACK": {},
                "TOWELS_PR_TOWELS": {},
                "TRAINING_GEAR_PR_DAILYTRAINING": {},
                "TRAINING_GEAR_PR_TRAININGGEAR": {},
                "WOOL_GOLD_PR_WOOL": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:help-circle",
        friendly_name="Program",
    ),
    # User Selections - Number controls
    "userSelections/antiCreaseValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 30,
            "max": 120,
            "min": 30,
            "step": 30,
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-Crease Duration",
    ),
    "userSelections/dryingTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 300,
            "min": 0,
            "step": 10,
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:clock-outline",
        friendly_name="Timed Drying",
    ),
    # User Selections - Select controls
    "userSelections/humidityTarget": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "CUPBOARD": {},
                "EXTRA": {},
                "IRON": {},
                "STRONG": {},
                "UNDEFINED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-percent",
        friendly_name="Dryness Level (Humidity Target)",
    ),
    "userSelections/drynessValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "MAXIMUM": {},
                "MEDIUM": {},
                "MINIMUM": {},
                "UNDEFINED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-percent",
        friendly_name="Dryness Intensity",
    ),
    "userSelections/steamValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": "STEAM_OFF",
            "type": "string",
            "values": {
                "STEAM_MAX": {},
                "STEAM_MED": {},
                "STEAM_MIN": {},
                "STEAM_OFF": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-partly-cloudy",
        friendly_name="Steam Level",
    ),
    # User Selections - Boolean switches/options
    "userSelections/reversePlus": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-3d-variant",
        friendly_name="Reverse Plus",
    ),
    "userSelections/tDEconomy_Eco": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:leaf",
        friendly_name="Eco Mode",
    ),
    "userSelections/tDEconomy_Night": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-night",
        friendly_name="Night Mode",
    ),
    "userSelections/tDEconomy_Quick": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lightning-bolt",
        friendly_name="Quick Mode",
    ),
    "userSelections/refresh": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:refresh",
        friendly_name="Refresh Program",
    ),
    # Cycle personalization (for cycleMemory)
    "cyclePersonalization/programUID": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "AUTO_EASY_IRON_PR_EASYIRON_TD": {},
                "BABY_PR_BABY": {},
                "BED_LINEN_PLUS_PR_BEDLINENPLUS": {},
                "BED_LINEN_PLUS_PR_BEDLINENPLUSITA": {},
                "COTTON_PR_COTTONS": {},
                "COTTON_PR_COTTONSECO": {},
                "COTTON_PR_ECO": {},
                "CURTAINS_PR_CURTAINS": {},
                "DOWN_JACKET_PR_DOWN_JACKET": {},
                "DRY_CLEANING_PR_REFRESH": {},
                "DUVET_PR_DUVET": {},
                "EXTRA_DELICATE_PR_DELICATES": {},
                "HYGIENE_PR_HYGIENE": {},
                "JEANS_PR_DENIM": {},
                "JEANS_PR_JEANS": {},
                "LINEN_PR_LINEN": {},
                "MY_DRY_PR_MIXCARE": {},
                "MY_DRY_PR_MIXDRY": {},
                "NA_ALLERGEN_PR_ALLERGEN": {},
                "ONE_ITEM_FAST_PR_ONEITEMFAST": {},
                "OUTD_PROOF_PR_OUTDOOR": {},
                "PETBED_PR_PETHAIR": {},
                "PILLOWS_PR_PILLOW": {},
                "QUICK_PR_QUICK_3KG": {},
                "QUICK_PR_RAPID_3KG": {},
                "SILK_DRY_PR_SILK": {},
                "SKIING_PR_SKIINGGEAR": {},
                "SOCCER_RUGBY_PR_SOCCER_RUGBY": {},
                "SPORTWEAR_PR_SPORTWEAR": {},
                "SYNTHETIC_PR_SYNTHETICS": {},
                "TIMEDRY_PR_DRYINGRACK": {},
                "TOWELS_PR_TOWELS": {},
                "TRAINING_GEAR_PR_DAILYTRAINING": {},
                "TRAINING_GEAR_PR_TRAININGGEAR": {},
                "WOOL_GOLD_PR_WOOL": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cog",
        friendly_name="Cycle Personalization Program",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/antiCreaseValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 30,
            "max": 120,
            "min": 30,
            "step": 30,
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Cycle Personalization Anti-Crease",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/dryingTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 300,
            "min": 0,
            "step": 10,
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:clock-outline",
        friendly_name="Cycle Personalization Drying Time",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/humidityTarget": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "CUPBOARD": {},
                "EXTRA": {},
                "IRON": {},
                "STRONG": {},
                "UNDEFINED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-percent",
        friendly_name="Cycle Personalization Humidity Target",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/drynessValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "MAXIMUM": {},
                "MEDIUM": {},
                "MINIMUM": {},
                "UNDEFINED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-percent",
        friendly_name="Cycle Personalization Dryness",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/reversePlus": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-3d-variant",
        friendly_name="Cycle Personalization Reverse Plus",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/tDEconomy_Eco": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:leaf",
        friendly_name="Cycle Personalization Eco",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/tDEconomy_Night": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-night",
        friendly_name="Cycle Personalization Night",
        entity_registry_enabled_default=False,
    ),
    "cyclePersonalization/tDEconomy_Quick": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": False,
            "type": "boolean",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lightning-bolt",
        friendly_name="Cycle Personalization Quick",
        entity_registry_enabled_default=False,
    ),
}
