"""Defined catalog of entities for washing machine type devices."""

from homeassistant.components.binary_sensor import BinarySensorDeviceClass
from homeassistant.components.button import ButtonDeviceClass
from homeassistant.components.number import NumberDeviceClass
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.components.switch import SwitchDeviceClass
from homeassistant.const import UnitOfMass, UnitOfTime
from homeassistant.helpers.entity import EntityCategory

from .const import (
    AUTODOSE_DETERGENT_DUAL_OFF,
    AUTODOSE_DETERGENT_DUAL_ON,
    AUTODOSE_LINK_OFF,
    AUTODOSE_LINK_ON,
    AUTODOSE_OFF,
    AUTODOSE_SOFTENER_OFF,
    AUTODOSE_SOFTENER_ON,
)
from .model import ElectroluxDevice

CATALOG_WASHER: dict[str, ElectroluxDevice] = {
    # Legacy/basic controls for backward compatibility with older models
    "preWashPhase": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "reminderTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 1200,
            "max": 2700,
            "min": 1200,
            "step": 60,
            "type": "number",
        },
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timelapse",
        entity_registry_enabled_default=False,
    ),
    "ui2LockMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "boolean",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lock",
    ),
    "vacationHolidayMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "boolean",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:airplane",
    ),
    # Basic controls
    "defaultExtraRinse": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"EXTRA_RINSE_1": {}, "EXTRA_RINSE_OFF": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "executeCommand": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "string",
            "values": {
                "OFF": {},
                "ON": {},
                "PAUSE": {},
                "RESUME": {},
                "START": {},
                "STOPRESET": {},
            },
        },
        device_class=ButtonDeviceClass.RESTART,
        unit=None,
        entity_category=None,
        entity_icon="mdi:play-pause",
    ),
    # Appliance state and cycle information
    "applianceState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ALARM": {},
                "DELAYED_START": {},
                "END_OF_CYCLE": {},
                "IDLE": {},
                "OFF": {},
                "PAUSED": {},
                "READY_TO_START": {},
                "RUNNING": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "cyclePhase": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ANTICREASE": {},
                "DRAIN": {},
                "DRY": {},
                "PREWASH": {},
                "RINSE": {},
                "SPIN": {},
                "STEAM": {},
                "WASH": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "cycleSubPhase": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ADD_GARMENT": {},
                "RINSE": {},
                "RINSE_HOLD": {},
                "SOAKING": {},
                "WASH": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "measuredLoadWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
        friendly_name="Measured Load Weight",
    ),
    # Door and lock status
    "doorState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"CLOSED": {}, "OPEN": {}},
        },
        device_class=BinarySensorDeviceClass.DOOR,
        unit=None,
        entity_category=None,
        entity_icon="mdi:door",
    ),
    "doorLock": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"LOCKING": {}, "OFF": {}, "ON": {}, "UNLOCKING": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lock",
    ),
    # Time and duration controls
    "startTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "max": 72000,
            "min": 0,
            "step": 1800,
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:clock-start",
    ),
    "stopTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "max": 86400,
            "min": 0,
            "step": 1800,
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:clock-end",
        friendly_name="Stop Time",
    ),
    # Statistics and counters
    "totalWashCyclesCount": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
    ),
    "totalWashingTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:timelapse",
    ),
    # Load and weight sensors
    "fcOptisenseLoadWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
    ),
    "washingNominalLoadWeight": ElectroluxDevice(
        capability_info={
            "access": "read",
            "max": 20000,
            "min": 0,
            "type": "number",
        },
        device_class=SensorDeviceClass.WEIGHT,
        unit=UnitOfMass.GRAMS,
        entity_category=None,
        entity_icon="mdi:weight",
    ),
    # Auto-dosing system
    "autoDosing/adTankAConfiguration": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"DETERGENT_DUAL": {}, "DISABLED": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Tank A Configuration",
    ),
    "autoDosing/adTankBConfiguration": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DETERGENT_DUAL": {},
                "DISABLED": {},
                "LINK": {},
                "SOFTENER": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Tank B Configuration",
    ),
    "autoDosing/adTankADetStandardDose": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 110,
            "max": 200,
            "min": 5,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:cup-water",
        friendly_name="Tank A Detergent Dose",
    ),
    "autoDosing/adTankBDetStandardDose": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 110,
            "max": 200,
            "min": 5,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:cup-water",
        friendly_name="Tank B Detergent Dose",
    ),
    "autoDosing/adTankBSoftStandardDose": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 25,
            "max": 100,
            "min": 5,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:cup-water",
        friendly_name="Tank B Softener Dose",
    ),
    # User selections
    "userSelections/steamValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": "STEAM_OFF",
            "type": "string",
            "values": {
                "STEAM_MAX": {},
                "STEAM_MED": {},
                "STEAM_MIN": {},
                "STEAM_OFF": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-partly-cloudy",
    ),
    "userSelections/timeManagerLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DAILY": {},
                "NORMAL": {},
                "SUPER_QUICK": {},
                "TIME_MANAGER_LEV_1": {},
                "TIME_MANAGER_LEV_4": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:speedometer",
    ),
    "userSelections/adTankASel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Auto-Dose Tank A",
    ),
    "userSelections/adTankBSel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
                AUTODOSE_SOFTENER_OFF: {},
                AUTODOSE_SOFTENER_ON: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Auto-Dose Tank B",
    ),
    "userSelections/adFineTuneDetLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "FINE_TUNE_DET_LEV_1": {},
                "FINE_TUNE_DET_LEV_3": {},
                "FINE_TUNE_DET_LEV_5": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tune",
        friendly_name="Detergent Fine Tune",
    ),
    "userSelections/adFineTuneSoftLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"FINE_TUNE_SOFT_LEV_1": {}, "FINE_TUNE_SOFT_NOT_AVAILABLE": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tune",
        friendly_name="Softener Fine Tune",
    ),
    "userSelections/analogSpinSpeed": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "0_RPM": {},
                "400_RPM": {},
                "600_RPM": {},
                "800_RPM": {},
                "1000_RPM": {},
                "1200_RPM": {},
                "1400_RPM": {},
                "1600_RPM": {},
                "DISABLED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-right",
    ),
    "userSelections/analogTemperature": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "20_CELSIUS": {},
                "30_CELSIUS": {},
                "40_CELSIUS": {},
                "50_CELSIUS": {},
                "60_CELSIUS": {},
                "90_CELSIUS": {},
                "COLD": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
    ),
    "userSelections/extraRinseNumber": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"NONE": {}, "ONE": {}, "TWO": {}, "THREE": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Extra Rinse Number",
    ),
    "userSelections/anticreaseNoSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-Crease No Steam",
    ),
    "userSelections/anticreaseWSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-Crease With Steam",
    ),
    "userSelections/nightCycle": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:moon-waning-crescent",
        friendly_name="Night Cycle",
    ),
    "userSelections/wmEconomy": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cash",
        friendly_name="Economy Mode",
    ),
    "userSelections/rinseHold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-pause",
        friendly_name="Rinse Hold",
    ),
    "userSelections/intensive": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:power-high",
        friendly_name="Intensive Wash",
    ),
    "userSelections/tcSensor": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature Sensor",
    ),
    "waterHardness": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "STEP_1": {},
                "STEP_2": {},
                "STEP_3": {},
                "STEP_4": {},
                "STEP_5": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:water",
        friendly_name="Water Hardness",
    ),
    "waterSoftenerMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"ALWAYS": {}, "WASH_ONLY": {}},
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:water-softener",
        friendly_name="Water Softener Mode",
    ),
    "displayLight": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DISPLAY_LIGHT_0": {},
                "DISPLAY_LIGHT_1": {},
                "DISPLAY_LIGHT_2": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lightbulb",
        friendly_name="Display Light",
    ),
    "networkInterface/otaState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "DESCRIPTION_AVAILABLE": {},
                "DESCRIPTION_DOWNLOADING": {},
                "DESCRIPTION_READY": {},
                "FW_DOWNLOADING": {},
                "FW_DOWNLOAD_START": {},
                "FW_SIGNATURE_CHECK": {},
                "FW_UPDATE_IN_PROGRESS": {},
                "IDLE": {},
                "READY_TO_UPDATE": {},
                "UPDATE_ABORT": {},
                "UPDATE_CHECK": {},
                "UPDATE_ERROR": {},
                "UPDATE_OK": {},
                "WAITINGFORAUTHORIZATION": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:update",
    ),
    # Maintenance system (simplified - showing key maintenance items)
    "applianceCareAndMaintenance0/maint1_ID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:wrench",
        friendly_name="Maintenance Item 1 ID",
    ),
    "applianceCareAndMaintenance0/maint1_occured": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Maintenance Item 1 Occurred",
    ),
    "applianceCareAndMaintenance0/maint1_threshold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "int"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:gauge",
        friendly_name="Maintenance Item 1 Threshold",
    ),
    # Miscellaneous state sensors
    "fCMiscellaneousState/detergentExtradosage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:cup-water",
        friendly_name="Detergent Extradosage",
    ),
    "fCMiscellaneousState/optisenseResult": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:eye",
        friendly_name="Optisense Result",
    ),
    "fCMiscellaneousState/softenerExtradosage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:cup-water",
        friendly_name="Softener Extradosage",
    ),
    "fCMiscellaneousState/tankADetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank A Load for Nominal Weight",
    ),
    "fCMiscellaneousState/tankAReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank A Reserve",
    ),
    "fCMiscellaneousState/tankBDetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank B Load for Nominal Weight",
    ),
    "fCMiscellaneousState/tankBReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank B Reserve",
    ),
    "fCMiscellaneousState/waterUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Water Usage",
    ),
}
