"""Defined catalog of entities for washer-dryer type devices."""

from homeassistant.components.binary_sensor import BinarySensorDeviceClass
from homeassistant.components.button import ButtonDeviceClass
from homeassistant.components.number import NumberDeviceClass
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.components.switch import SwitchDeviceClass
from homeassistant.const import UnitOfMass, UnitOfTime
from homeassistant.helpers.entity import EntityCategory

from .const import (
    AUTODOSE_DETERGENT_DUAL_OFF,
    AUTODOSE_DETERGENT_DUAL_ON,
    AUTODOSE_LINK_OFF,
    AUTODOSE_LINK_ON,
    AUTODOSE_OFF,
    AUTODOSE_SOFTENER_OFF,
)
from .model import ElectroluxDevice

CATALOG_WASHER_DRYER: dict[str, ElectroluxDevice] = {
    # Legacy/basic controls for backward compatibility with older models
    "preWashPhase": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "reminderTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 1200,
            "max": 2700,
            "min": 1200,
            "step": 60,
            "type": "number",
        },
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timelapse",
        entity_registry_enabled_default=False,
    ),
    "ui2LockMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lock",
    ),
    "vacationHolidayMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:airplane",
    ),
    # Basic controls
    "defaultExtraRinse": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"EXTRA_RINSE_1": {}, "EXTRA_RINSE_OFF": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "executeCommand": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "string",
            "values": {
                "OFF": {},
                "ON": {},
                "PAUSE": {},
                "RESUME": {},
                "START": {},
                "STOPRESET": {},
            },
        },
        device_class=ButtonDeviceClass.RESTART,
        unit=None,
        entity_category=None,
        entity_icon="mdi:play-pause",
    ),
    "applianceState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ALARM": {},
                "DELAYED_START": {},
                "END_OF_CYCLE": {},
                "IDLE": {},
                "OFF": {},
                "PAUSED": {},
                "READY_TO_START": {},
                "RUNNING": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "cyclePhase": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ANTICREASE": {},
                "DRAIN": {},
                "DRY": {},
                "PREWASH": {},
                "RINSE": {},
                "SPIN": {},
                "STEAM": {},
                "WASH": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-right",
        friendly_name="Cycle Phase",
    ),
    "stopTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "max": 86400,
            "min": 0,
            "step": 1800,
            "type": "number",
        },
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=None,
        entity_icon="mdi:camera-timer",
        friendly_name="Stop Time",
    ),
    # Load weight sensors
    "dryingNominalLoadWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=UnitOfMass.KILOGRAMS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:weight-kilogram",
        friendly_name="Drying Load Weight",
    ),
    "washingNominalLoadWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=UnitOfMass.KILOGRAMS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:weight-kilogram",
        friendly_name="Washing Load Weight",
    ),
    # User selections
    "userSelections/EWX1493A_dryMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hair-dryer",
        friendly_name="Dry Mode",
    ),
    "userSelections/dryingTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 300,
            "min": 0,
            "step": 10,
            "type": "number",
        },
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:clock-outline",
        friendly_name="Drying Time",
    ),
    "userSelections/humidityTarget": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "CUPBOARD": {},
                "EXTRA": {},
                "IRON": {},
                "UNDEFINED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-percent",
        friendly_name="Dryness Level",
    ),
    "userSelections/EWX1493A_wetMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water",
        friendly_name="Wet Mode",
    ),
    "userSelections/steamValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": "STEAM_OFF",
            "type": "string",
            "values": {
                "STEAM_MAX": {},
                "STEAM_MED": {},
                "STEAM_MIN": {},
                "STEAM_OFF": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-partly-cloudy",
        friendly_name="Steam Level",
    ),
    "userSelections/timeManagerLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DAILY": {},
                "NORMAL": {},
                "SUPER_QUICK": {},
                "TIME_MANAGER_LEV_1": {},
                "TIME_MANAGER_LEV_4": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:speedometer",
        friendly_name="Time Manager",
    ),
    "userSelections/EWX1493A_pod": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cup",
        friendly_name="POD",
    ),
    "userSelections/EWX1493A_preWashPhase": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Pre-wash",
    ),
    "userSelections/EWX1493A_stain": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:stain",
        friendly_name="Stain Treatment",
    ),
    "userSelections/EWX1493A_steamMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-partly-cloudy",
        friendly_name="Steam Mode",
    ),
    "userSelections/analogSpinSpeed": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-right",
        friendly_name="Spin Speed",
    ),
    "userSelections/analogTemperature": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature",
    ),
    "userSelections/extraRinseNumber": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 3,
            "min": 0,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Extra Rinses",
    ),
    "userSelections/EWX1493A_anticreaseNoSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-crease (No Steam)",
    ),
    "userSelections/EWX1493A_nightCycle": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:moon-waning-crescent",
        friendly_name="Night Cycle",
    ),
    "userSelections/EWX1493A_rinseHold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-pause",
        friendly_name="Rinse Hold",
    ),
    "userSelections/memoryId": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:content-save",
        friendly_name="Memory Slot",
    ),
    "userSelections/adTankASel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Auto-Dose Tank A",
    ),
    "userSelections/adTankBSel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Auto-Dose Tank B",
    ),
    "userSelections/adFineTuneDetLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 4,
            "min": -4,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask-outline",
        friendly_name="Fine Tune Detergent Level",
    ),
    "userSelections/adFineTuneSoftLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 4,
            "min": -4,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask-outline",
        friendly_name="Fine Tune Softener Level",
    ),
    "userSelections/intensive": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:power-high",
        friendly_name="Intensive",
    ),
    "userSelections/tcSensor": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature Sensor",
    ),
    "userSelections/wmEconomy": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cash",
        friendly_name="Economy Mode",
    ),
    # Tank levels and maintenance
    "tankALevel": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Tank A Level",
    ),
    "tankBLevel": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Tank B Level",
    ),
    "tankADetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank A Load for Nominal Weight",
    ),
    "tankBDetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank B Load for Nominal Weight",
    ),
    "fCMiscellaneousState/tankAReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank A Reserve",
    ),
    "fCMiscellaneousState/tankBReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank B Reserve",
    ),
    "fCMiscellaneousState/waterUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Water Usage",
    ),
    # Appliance software versions
    "applianceMainBoardSwVersion": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:chip",
        friendly_name="Main Board SW Version",
        entity_registry_enabled_default=False,
    ),
    "applianceUiSwVersion": ElectroluxDevice(
        capability_info={"access": "read", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:application-cog",
        friendly_name="UI SW Version",
        entity_registry_enabled_default=False,
    ),
    # Appliance mode
    "applianceMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DEMO": {},
                "DIAGNOSTIC": {},
                "NORMAL": {},
                "SERVICE": {},
            },
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:cog",
        friendly_name="Appliance Mode",
        entity_registry_enabled_default=False,
    ),
    # Network settings
    "networkInterfaceAlwaysOn": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:wifi-check",
        friendly_name="Network Always On",
    ),
    "remoteNotificationPending": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:bell-ring",
        friendly_name="Remote Notification Pending",
        entity_registry_enabled_default=False,
    ),
    # Door state
    "doorState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {"CLOSED": {}, "OPEN": {}},
        },
        device_class=BinarySensorDeviceClass.DOOR,
        unit=None,
        entity_category=None,
        friendly_name="Door",
    ),
    # Cycle sub phase
    "cycleSubPhase": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ADD_GARMENT": {},
                "NOT_AVAILABLE": {},
                "RINSE": {},
                "RINSE_HOLD": {},
                "SAFETY_COOL_DOWN": {},
                "SOAKING": {},
            },
        },
        device_class=SensorDeviceClass.ENUM,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Cycle Sub-phase",
    ),
    # Timing
    "minFinishInTime": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {"INVALID_OR_NOT_SET_TIME": {}},
        },
        device_class=None,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:clock-end",
        friendly_name="Min Finish In Time",
        entity_registry_enabled_default=False,
    ),
    # Load weight
    "fcOptisenseLoadWeight": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "number",
            "values": {
                "65408": {},
                "65409": {},
                "65410": {},
                "65411": {},
                "65412": {},
                "NOT_AVAILABLE": {},
            },
        },
        device_class=None,
        unit=UnitOfMass.GRAMS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:weight",
        friendly_name="Optisense Load Weight",
    ),
    # Cycle statistics
    "totalDryCyclesCount": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Total Dry Cycles",
    ),
    "totalDryingTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timer",
        friendly_name="Total Drying Time",
    ),
    "totalWashCyclesCount": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Total Wash Cycles",
    ),
    "totalWashDryCyclesCount": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:counter",
        friendly_name="Total Wash+Dry Cycles",
    ),
    "totalWashingTime": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timer",
        friendly_name="Total Washing Time",
    ),
    # Auto dosing
    "autoDosing/adLocalFineTuning": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:tune",
        friendly_name="Auto Dose Local Fine Tuning",
    ),
    "autoDosing/adTankAConfiguration": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DETERGENT_DUAL": {},
                "DISABLED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask-empty",
        friendly_name="Tank A Configuration",
    ),
    "autoDosing/adTankADetStandardDose": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask",
        friendly_name="Tank A Detergent Standard Dose",
    ),
    "autoDosing/adTankBConfiguration": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DETERGENT_DUAL": {},
                "DISABLED": {},
                "LINK": {},
                "SOFTENER": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask-empty",
        friendly_name="Tank B Configuration",
    ),
    "autoDosing/adTankBDetStandardDose": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask",
        friendly_name="Tank B Detergent Standard Dose",
    ),
    "autoDosing/adTankBSoftStandardDose": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank B Softener Standard Dose",
    ),
    # fCMiscellaneousState auto dosing sub-fields
    "fCMiscellaneousState/adTankADetLoaded": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank A Detergent Loaded",
    ),
    "fCMiscellaneousState/adTankBDetLoaded": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank B Detergent Loaded",
    ),
    "fCMiscellaneousState/adTankBSoftLoaded": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank B Softener Loaded",
    ),
    "fCMiscellaneousState/detergentExtradosage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:plus-circle",
        friendly_name="Detergent Extra Dosage",
        entity_registry_enabled_default=False,
    ),
    "fCMiscellaneousState/ecoLevel": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:leaf",
        friendly_name="Eco Level",
        entity_registry_enabled_default=False,
    ),
    "fCMiscellaneousState/softenerExtradosage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:plus-circle-outline",
        friendly_name="Softener Extra Dosage",
        entity_registry_enabled_default=False,
    ),
    "fCMiscellaneousState/tankADetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank A Det Load For Nominal Weight",
        entity_registry_enabled_default=False,
    ),
    "fCMiscellaneousState/tankBDetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank B Det Load For Nominal Weight",
        entity_registry_enabled_default=False,
    ),
    # Clear cycle personalization command
    "clearCyclePersonalizationCmd": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "number",
            "values": {"0": {}},
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:restore",
        friendly_name="Clear Cycle Personalization",
        entity_registry_enabled_default=False,
    ),
    # Cycle personalization entries
    "cyclePersonalization/EWX1493A_anticreaseNoSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:iron",
        friendly_name="Anti-crease (No Steam)",
    ),
    "cyclePersonalization/EWX1493A_dryMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tumble-dryer",
        friendly_name="Dry Mode",
    ),
    "cyclePersonalization/EWX1493A_nightCycle": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-night",
        friendly_name="Night Cycle",
    ),
    "cyclePersonalization/EWX1493A_pod": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:package-variant",
        friendly_name="Pod Detergent",
    ),
    "cyclePersonalization/EWX1493A_preWashPhase": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-sync",
        friendly_name="Pre-wash Phase",
    ),
    "cyclePersonalization/EWX1493A_rinseHold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-pause",
        friendly_name="Rinse Hold",
    ),
    "cyclePersonalization/EWX1493A_stain": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:sticker-alert",
        friendly_name="Stain Removal",
    ),
    "cyclePersonalization/EWX1493A_steamMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-fog",
        friendly_name="Steam Mode",
    ),
    "cyclePersonalization/EWX1493A_wetMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water",
        friendly_name="Wet Mode",
    ),
    "cyclePersonalization/adFineTuneDetLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "FINE_TUNE_DET_LEV_1": {},
                "FINE_TUNE_DET_LEV_3": {},
                "FINE_TUNE_DET_LEV_5": {},
                "FINE_TUNE_DET_NOT_AVAILABLE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:tune",
        friendly_name="Auto Dose Detergent Fine Tune",
    ),
    "cyclePersonalization/adFineTuneSoftLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "FINE_TUNE_SOFT_LEV_1": {},
                "FINE_TUNE_SOFT_NOT_AVAILABLE": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:tune",
        friendly_name="Auto Dose Softener Fine Tune",
    ),
    "cyclePersonalization/adTankASel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
                AUTODOSE_SOFTENER_OFF: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask-empty",
        friendly_name="Tank A Auto Dose Selection",
    ),
    "cyclePersonalization/adTankBSel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                AUTODOSE_DETERGENT_DUAL_OFF: {},
                AUTODOSE_DETERGENT_DUAL_ON: {},
                AUTODOSE_LINK_OFF: {},
                AUTODOSE_LINK_ON: {},
                AUTODOSE_OFF: {},
                AUTODOSE_SOFTENER_OFF: {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=EntityCategory.CONFIG,
        entity_icon="mdi:flask",
        friendly_name="Tank B Auto Dose Selection",
    ),
    "cyclePersonalization/analogSpinSpeed": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "0_RPM": {},
                "400_RPM": {},
                "1000_RPM": {},
                "1200_RPM": {},
                "1400_RPM": {},
                "1600_RPM": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-orbit",
        friendly_name="Spin Speed",
    ),
    "cyclePersonalization/analogTemperature": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "20_CELSIUS": {},
                "30_CELSIUS": {},
                "40_CELSIUS": {},
                "50_CELSIUS": {},
                "60_CELSIUS": {},
                "95_CELSIUS": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature",
    ),
    "cyclePersonalization/dryingTime": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "number"},
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:tumble-dryer",
        friendly_name="Drying Time",
    ),
    "cyclePersonalization/humidityTarget": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "CUPBOARD": {},
                "EXTRA": {},
                "IRON": {},
                "UNDEFINED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-percent",
        friendly_name="Humidity Target",
    ),
    "cyclePersonalization/programUID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Cycle Program",
    ),
    "cyclePersonalization/timeManagerLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DAILY": {},
                "NORMAL": {},
                "SUPER_QUICK": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:speedometer",
        friendly_name="Time Manager",
    ),
}
