"""Defined catalog of entities for washer-dryer type devices."""

from homeassistant.components.binary_sensor import BinarySensorDeviceClass
from homeassistant.components.button import ButtonDeviceClass
from homeassistant.components.number import NumberDeviceClass
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.components.switch import SwitchDeviceClass
from homeassistant.const import UnitOfMass, UnitOfTime
from homeassistant.helpers.entity import EntityCategory

from .model import ElectroluxDevice

CATALOG_WASHER_DRYER: dict[str, ElectroluxDevice] = {
    # Legacy/basic controls for backward compatibility with older models
    "preWashPhase": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "reminderTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 1200,
            "max": 2700,
            "min": 1200,
            "step": 60,
            "type": "number",
        },
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.SECONDS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:timelapse",
        entity_registry_enabled_default=False,
    ),
    "ui2LockMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "boolean",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:lock",
    ),
    "vacationHolidayMode": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "boolean",
            "values": {"OFF": {}, "ON": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:airplane",
    ),
    # Alert system - individual binary sensors for each alert type
    "alerts/CHECK_DOOR": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:alert-circle",
        friendly_name="Check Door",
    ),
    "alerts/CHECK_DRAIN_FILTER": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:filter",
        friendly_name="Check Drain Filter",
    ),
    "alerts/CHECK_INLET_TAP": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-pump",
        friendly_name="Check Inlet Tap",
    ),
    "alerts/CLEAN_FLUFF_DRAWER": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:delete-variant",
        friendly_name="Clean Fluff Drawer",
    ),
    "alerts/DETERGENT_OVERDOSING": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:cup-water",
        friendly_name="Detergent Overdosing",
    ),
    "alerts/DOOR": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.DOOR,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:door-open",
        friendly_name="Door Alert",
    ),
    "alerts/EMPTY_WATER_CONTAINER": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-off",
        friendly_name="Empty Water Container",
    ),
    "alerts/MACHINE_RESTART": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:restart",
        friendly_name="Machine Restart",
    ),
    "alerts/POWER_FAILURE": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:power-plug-off",
        friendly_name="Power Failure",
    ),
    "alerts/STEAM_TANK_FULL": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:weather-cloudy",
        friendly_name="Steam Tank Full",
    ),
    "alerts/TOP_UP_SALT": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:shaker",
        friendly_name="Top Up Salt",
    ),
    "alerts/UNBALANCED_LAUNDRY": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:scale-unbalanced",
        friendly_name="Unbalanced Laundry",
    ),
    "alerts/UNSTABLE_SUPPLY_VOLTAGE": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flash",
        friendly_name="Unstable Supply Voltage",
    ),
    "alerts/WATER_CONTAINER": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Water Container",
    ),
    "alerts/WATER_LEAK": ElectroluxDevice(
        capability_info={"access": "read", "type": "alert"},
        device_class=BinarySensorDeviceClass.PROBLEM,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water-alert",
        friendly_name="Water Leak",
    ),
    # Basic controls
    "defaultExtraRinse": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"EXTRA_RINSE_1": {}, "EXTRA_RINSE_OFF": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "endOfCycleSound": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {"NO_SOUND": {}, "SHORT_SOUND": {}},
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:volume-high",
    ),
    "executeCommand": ElectroluxDevice(
        capability_info={
            "access": "write",
            "type": "string",
            "values": {
                "OFF": {},
                "ON": {},
                "PAUSE": {},
                "RESUME": {},
                "START": {},
                "STOPRESET": {},
            },
        },
        device_class=ButtonDeviceClass.RESTART,
        unit=None,
        entity_category=None,
        entity_icon="mdi:play-pause",
    ),
    "applianceState": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ALARM": {},
                "DELAYED_START": {},
                "END_OF_CYCLE": {},
                "IDLE": {},
                "OFF": {},
                "PAUSED": {},
                "READY_TO_START": {},
                "RUNNING": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
    ),
    "cyclePhase": ElectroluxDevice(
        capability_info={
            "access": "read",
            "type": "string",
            "values": {
                "ANTICREASE": {},
                "DRAIN": {},
                "DRY": {},
                "PREWASH": {},
                "RINSE": {},
                "SPIN": {},
                "STEAM": {},
                "WASH": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-right",
        friendly_name="Cycle Phase",
    ),
    "timeToEnd": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=SensorDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:clock-end",
        friendly_name="Time to End",
    ),
    # Load weight sensors
    "dryingNominalLoadWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=UnitOfMass.KILOGRAMS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:weight-kilogram",
        friendly_name="Drying Load Weight",
    ),
    "washingNominalLoadWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=UnitOfMass.KILOGRAMS,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:weight-kilogram",
        friendly_name="Washing Load Weight",
    ),
    # User selections
    "userSelections/programUID": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:tune",
        friendly_name="Program",
    ),
    "userSelections/EWX1493A_dryMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hair-dryer",
        friendly_name="Dry Mode",
    ),
    "userSelections/dryingTime": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 300,
            "min": 0,
            "step": 10,
            "type": "number",
        },
        device_class=NumberDeviceClass.DURATION,
        unit=UnitOfTime.MINUTES,
        entity_category=None,
        entity_icon="mdi:clock-outline",
        friendly_name="Drying Time",
    ),
    "userSelections/humidityTarget": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "CUPBOARD": {},
                "EXTRA": {},
                "IRON": {},
                "UNDEFINED": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-percent",
        friendly_name="Dryness Level",
    ),
    "userSelections/EWX1493A_wetMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water",
        friendly_name="Wet Mode",
    ),
    "userSelections/steamValue": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": "STEAM_OFF",
            "type": "string",
            "values": {
                "STEAM_MAX": {},
                "STEAM_MED": {},
                "STEAM_MIN": {},
                "STEAM_OFF": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-partly-cloudy",
        friendly_name="Steam Level",
    ),
    "userSelections/timeManagerLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "DAILY": {},
                "NORMAL": {},
                "SUPER_QUICK": {},
                "TIME_MANAGER_LEV_1": {},
                "TIME_MANAGER_LEV_4": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:speedometer",
        friendly_name="Time Manager",
    ),
    "userSelections/EWX1493A_pod": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cup",
        friendly_name="POD",
    ),
    "userSelections/EWX1493A_preWashPhase": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Pre-wash",
    ),
    "userSelections/EWX1493A_stain": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:stain",
        friendly_name="Stain Treatment",
    ),
    "userSelections/EWX1493A_steamMode": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:weather-partly-cloudy",
        friendly_name="Steam Mode",
    ),
    "userSelections/analogSpinSpeed": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:rotate-right",
        friendly_name="Spin Speed",
    ),
    "userSelections/analogTemperature": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "string"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature",
    ),
    "userSelections/extraRinseNumber": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 3,
            "min": 0,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:washing-machine",
        friendly_name="Extra Rinses",
    ),
    "userSelections/EWX1493A_anticreaseNoSteam": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:hanger",
        friendly_name="Anti-crease (No Steam)",
    ),
    "userSelections/EWX1493A_nightCycle": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:moon-waning-crescent",
        friendly_name="Night Cycle",
    ),
    "userSelections/EWX1493A_rinseHold": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:water-pause",
        friendly_name="Rinse Hold",
    ),
    "userSelections/memoryId": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:content-save",
        friendly_name="Memory Slot",
    ),
    "userSelections/adTankASel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "AUTODOSE_DETERGENT_DUAL_OFF": {},
                "AUTODOSE_DETERGENT_DUAL_ON": {},
                "AUTODOSE_LINK_OFF": {},
                "AUTODOSE_LINK_ON": {},
                "AUTODOSE_OFF": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Auto-Dose Tank A",
    ),
    "userSelections/adTankBSel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "type": "string",
            "values": {
                "AUTODOSE_DETERGENT_DUAL_OFF": {},
                "AUTODOSE_DETERGENT_DUAL_ON": {},
                "AUTODOSE_LINK_OFF": {},
                "AUTODOSE_LINK_ON": {},
                "AUTODOSE_OFF": {},
            },
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Auto-Dose Tank B",
    ),
    "userSelections/adFineTuneDetLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 4,
            "min": -4,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask-outline",
        friendly_name="Fine Tune Detergent Level",
    ),
    "userSelections/adFineTuneSoftLevel": ElectroluxDevice(
        capability_info={
            "access": "readwrite",
            "default": 0,
            "max": 4,
            "min": -4,
            "step": 1,
            "type": "number",
        },
        device_class=None,
        unit=None,
        entity_category=None,
        entity_icon="mdi:flask-outline",
        friendly_name="Fine Tune Softener Level",
    ),
    "userSelections/intensive": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:power-high",
        friendly_name="Intensive",
    ),
    "userSelections/tcSensor": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:thermometer",
        friendly_name="Temperature Sensor",
    ),
    "userSelections/wmEconomy": ElectroluxDevice(
        capability_info={"access": "readwrite", "type": "boolean"},
        device_class=SwitchDeviceClass.SWITCH,
        unit=None,
        entity_category=None,
        entity_icon="mdi:cash",
        friendly_name="Economy Mode",
    ),
    # Tank levels and maintenance
    "tankALevel": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Tank A Level",
    ),
    "tankBLevel": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit="ml",
        entity_category=None,
        entity_icon="mdi:flask",
        friendly_name="Tank B Level",
    ),
    "tankADetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank A Load for Nominal Weight",
    ),
    "tankBDetLoadForNominalWeight": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask",
        friendly_name="Tank B Load for Nominal Weight",
    ),
    "fCMiscellaneousState/tankAReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank A Reserve",
    ),
    "fCMiscellaneousState/tankBReserve": ElectroluxDevice(
        capability_info={"access": "read", "type": "boolean"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:flask-outline",
        friendly_name="Tank B Reserve",
    ),
    "fCMiscellaneousState/waterUsage": ElectroluxDevice(
        capability_info={"access": "read", "type": "number"},
        device_class=None,
        unit=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_icon="mdi:water",
        friendly_name="Water Usage",
    ),
}
